(deftheme flatwhite "Flatwhite light theme")
(deftheme flatdark "Flatwhite dark theme")

(defvar flatwhite-colors
  '((base1 . "#605a52")
    (base2 . "#93836c")
    (base3 . "#b9a992")
    (base4 . "#dcd3c6")
    (base5 . "#e4ddd2")
    (base6 . "#f1ece4")
    (base7 . "#f7f3ee")
    (accent . "#6a4dff")
    (orange-text . "#5b5143")
    (orange-bg . "#f7e0c3")
    (green-text . "#525643")
    (green-bg . "#e2e9c1")
    (teal-text . "#465953")
    (teal-bg . "#d2ebe3")
    (blue-text . "#4c5361")
    (blue-bg . "#dde4f2")
    (purple-text . "#614c61")
    (purple-bg . "#f1ddf1")
    (added . "#2db448")
    (removed . "#ff1414")
    (modified . "#f2a60d")
    (renamed . "#52aeff"))
  "Flatwhite light theme colors.")

(defvar flatdark-colors
  '((base1 . "#D7DCE2")
    (base2 . "#AAB4C0")
    (base3 . "#88919E")
    (base4 . "#4B5563")
    (base5 . "#374151")
    (base6 . "#1F2937")
    (base7 . "#111827")
    (accent . "#7C7FFF")
    (orange-text . "#E0A96D")
    (orange-bg . "#5A4127")
    (green-text . "#9BD97C")
    (green-bg . "#2E4632")
    (teal-text . "#6ED8C4")
    (teal-bg . "#2A4543")
    (blue-text . "#7DA6F5")
    (blue-bg . "#263B5A")
    (purple-text . "#B893F6")
    (purple-bg . "#3B2D4D")
    (added . "#2db448")
    (removed . "#ff1414")
    (modified . "#f2a60d")
    (renamed . "#52aeff"))
  "Flatdark dark theme colors.")

(defun flatwhite-set-faces (colors)
  "Set faces for flatwhite theme using COLORS."
  (let* ((base7 (cdr (assoc 'base7 colors)))
         (base1 (cdr (assoc 'base1 colors)))
         (base3 (cdr (assoc 'base3 colors)))
         (base4 (cdr (assoc 'base4 colors)))
         (base5 (cdr (assoc 'base5 colors)))
         (accent (cdr (assoc 'accent colors)))
         (orange-text (cdr (assoc 'orange-text colors)))
         (orange-bg (cdr (assoc 'orange-bg colors)))
         (green-text (cdr (assoc 'green-text colors)))
         (green-bg (cdr (assoc 'green-bg colors)))
         (teal-text (cdr (assoc 'teal-text colors)))
         (teal-bg (cdr (assoc 'teal-bg colors)))
         (blue-text (cdr (assoc 'blue-text colors)))
         (blue-bg (cdr (assoc 'blue-bg colors)))
         (purple-text (cdr (assoc 'purple-text colors)))
         (purple-bg (cdr (assoc 'purple-bg colors)))
         (added (cdr (assoc 'added colors)))
         (removed (cdr (assoc 'removed colors)))
         (modified (cdr (assoc 'modified colors)))
         (renamed (cdr (assoc 'renamed colors))))
    (custom-theme-set-faces
     'flatwhite
     `(default ((t (:foreground ,base1 :background ,base7))))
     `(cursor ((t (:background ,accent))))
     `(line-number ((t (:foreground ,base3))))
     `(line-number-current-line ((t (:foreground ,base1))))
     `(region ((t (:background ,base4))))
     `(mode-line ((t (:foreground ,base1 :background ,base4))))
     `(mode-line-inactive ((t (:foreground ,base3 :background ,base4))))
     `(mode-line-buffer-id ((t (:weight bold))))
     `(vertical-border ((t (:background ,base4))))
     `(fringe ((t (:background ,base7 :foreground ,base3))))
     `(scroll-bar ((t (:background ,base4 :foreground ,base3))))
     `(highlight ((t (:background ,base5))))
     `(show-paren-match ((t (:background ,base4 :weight bold))))
     `(isearch ((t (:background ,base4 :weight bold))))
     `(isearch-lazy-highlight-face ((t (:background ,base5))))
     `(font-lock-comment-face ((t (:foreground ,base3))))
     `(font-lock-string-face ((t (:foreground ,green-text :background ,green-bg))))
     `(font-lock-keyword-face ((t (:foreground ,purple-text :background ,purple-bg))))
     `(font-lock-function-name-face ((t (:foreground ,blue-text :background ,blue-bg))))
     `(font-lock-variable-name-face ((t (:foreground ,base1))))
     `(font-lock-type-face ((t (:foreground ,orange-text :background ,orange-bg))))
     `(font-lock-constant-face ((t (:foreground ,teal-text :background ,teal-bg))))
     `(font-lock-number-face ((t (:foreground ,teal-text :background ,teal-bg))))
     `(font-lock-builtin-face ((t (:foreground ,teal-text :background ,teal-bg))))
     `(font-lock-doc-face ((t (:foreground ,base3))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,base3))))
     `(font-lock-warning-face ((t (:foreground ,removed :weight bold))))
     `(diff-added ((t (:background ,added :foreground ,base1))))
     `(diff-removed ((t (:background ,removed :foreground ,base7))))
     `(diff-changed ((t (:background ,modified :foreground ,base1))))
     `(diff-file-header ((t (:foreground ,base1 :weight bold))))
     `(diff-hunk-header ((t (:foreground ,base3))))
     `(diff-context ((t (:foreground ,base3))))
     `(diff-header ((t (:foreground ,base3))))
     `(org-level-1 ((t (:foreground ,base1 :weight bold))))
     `(org-level-2 ((t (:foreground ,base3 :weight bold))))
     `(org-block ((t (:background ,base5 :foreground ,base1))))
     `(org-quote ((t (:background ,base5 :foreground ,base1))))
     `(org-code ((t (:background ,base5 :foreground ,base1))))
     `(org-list-dt ((t (:foreground ,base1 :weight bold))))
     `(minibuffer-prompt ((t (:foreground ,base1))))
     `(error ((t (:foreground ,removed :weight bold))))
     `(warning ((t (:foreground ,modified :weight bold))))
     `(success ((t (:foreground ,added :weight bold))))
     `(diff-refine-added ((t (:background ,added :foreground ,base1))))
     `(diff-refine-removed ((t (:background ,removed :foreground ,base7))))
     `(diff-refine-changed ((t (:background ,modified :foreground ,base1))))
     `(diff-refine-header ((t (:foreground ,base3))))
     `(diff-refine-file-header ((t (:foreground ,base1 :weight bold))))
     `(diff-refine-context ((t (:foreground ,base3))))
     `(diff-refine-hunk-header ((t (:foreground ,base3))))
     `(diff-refine-unchanged ((t (:foreground ,base3))))
     ))

(defun flatdark-set-faces (colors)
  "Set faces for flatdark theme using COLORS."
  (let* ((base7 (cdr (assoc 'base7 colors)))
         (base1 (cdr (assoc 'base1 colors)))
         (base3 (cdr (assoc 'base3 colors)))
         (base4 (cdr (assoc 'base4 colors)))
         (base5 (cdr (assoc 'base5 colors)))
         (accent (cdr (assoc 'accent colors)))
         (orange-text (cdr (assoc 'orange-text colors)))
         (orange-bg (cdr (assoc 'orange-bg colors)))
         (green-text (cdr (assoc 'green-text colors)))
         (green-bg (cdr (assoc 'green-bg colors)))
         (teal-text (cdr (assoc 'teal-text colors)))
         (teal-bg (cdr (assoc 'teal-bg colors)))
         (blue-text (cdr (assoc 'blue-text colors)))
         (blue-bg (cdr (assoc 'blue-bg colors)))
         (purple-text (cdr (assoc 'purple-text colors)))
         (purple-bg (cdr (assoc 'purple-bg colors)))
         (added (cdr (assoc 'added colors)))
         (removed (cdr (assoc 'removed colors)))
         (modified (cdr (assoc 'modified colors)))
         (renamed (cdr (assoc 'renamed colors))))
    (custom-theme-set-faces
     'flatdark
     `(default ((t (:foreground ,base1 :background ,base7))))
     `(cursor ((t (:background ,accent))))
     `(line-number ((t (:foreground ,base3))))
     `(line-number-current-line ((t (:foreground ,base1))))
     `(region ((t (:background ,base4))))
     `(mode-line ((t (:foreground ,base1 :background ,base4))))
     `(mode-line-inactive ((t (:foreground ,base3 :background ,base4))))
     `(mode-line-buffer-id ((t (:weight bold))))
     `(vertical-border ((t (:background ,base4))))
     `(fringe ((t (:background ,base7 :foreground ,base3))))
     `(scroll-bar ((t (:background ,base4 :foreground ,base3))))
     `(highlight ((t (:background ,base5))))
     `(show-paren-match ((t (:background ,base4 :weight bold))))
     `(isearch ((t (:background ,base4 :weight bold))))
     `(isearch-lazy-highlight-face ((t (:background ,base5))))
     `(font-lock-comment-face ((t (:foreground ,base3))))
     `(font-lock-string-face ((t (:foreground ,green-text :background ,green-bg))))
     `(font-lock-keyword-face ((t (:foreground ,purple-text :background ,purple-bg))))
     `(font-lock-function-name-face ((t (:foreground ,blue-text :background ,blue-bg))))
     `(font-lock-variable-name-face ((t (:foreground ,base1))))
     `(font-lock-type-face ((t (:foreground ,orange-text :background ,orange-bg))))
     `(font-lock-constant-face ((t (:foreground ,teal-text :background ,teal-bg))))
     `(font-lock-number-face ((t (:foreground ,teal-text :background ,teal-bg))))
     `(font-lock-builtin-face ((t (:foreground ,teal-text :background ,teal-bg))))
     `(font-lock-doc-face ((t (:foreground ,base3))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,base3))))
     `(font-lock-warning-face ((t (:foreground ,removed :weight bold))))
     `(diff-added ((t (:background ,added :foreground ,base1))))
     `(diff-removed ((t (:background ,removed :foreground ,base1))))
     `(diff-changed ((t (:background ,modified :foreground ,base1))))
     `(diff-file-header ((t (:foreground ,base1 :weight bold))))
     `(diff-hunk-header ((t (:foreground ,base3))))
     `(diff-context ((t (:foreground ,base3))))
     `(diff-header ((t (:foreground ,base3))))
     `(org-level-1 ((t (:foreground ,base1 :weight bold))))
     `(org-level-2 ((t (:foreground ,base3 :weight bold))))
     `(org-block ((t (:background ,base5 :foreground ,base1))))
     `(org-quote ((t (:background ,base5 :foreground ,base1))))
     `(org-code ((t (:background ,base5 :foreground ,base1))))
     `(org-list-dt ((t (:foreground ,base1 :weight bold))))
     `(minibuffer-prompt ((t (:foreground ,base1))))
     `(error ((t (:foreground ,removed :weight bold))))
     `(warning ((t (:foreground ,modified :weight bold))))
     `(success ((t (:foreground ,added :weight bold))))
     `(diff-refine-added ((t (:background ,added :foreground ,base1))))
     `(diff-refine-removed ((t (:background ,removed :foreground ,base1))))
     `(diff-refine-changed ((t (:background ,modified :foreground ,base1))))
     `(diff-refine-header ((t (:foreground ,base3))))
     `(diff-refine-file-header ((t (:foreground ,base1 :weight bold))))
     `(diff-refine-context ((t (:foreground ,base3))))
     `(diff-refine-hunk-header ((t (:foreground ,base3))))
     `(diff-refine-unchanged ((t (:foreground ,base3))))
     ))

(flatwhite-set-faces flatwhite-colors)
(flatdark-set-faces flatdark-colors)

(provide-theme 'flatwhite)
(provide-theme 'flatdark)
